KratosMultiphysics/CoSimIO

- co_sim_io/impl/info.hpp
- co_sim_io/impl/macros.hpp
- tests/co_sim_io/internals/test_info.cpp
@pooyan-dadvand I think we need sth more elaborate for the memory-management if the `Info` object.
Not saving the memory but only the pointer messes things up
https://github.com/KratosMultiphysics/CoSimIO/blob/master/co_sim_io/impl/info.hpp#L30-L78
I don't fully understand how this works in Kratos (too many `Variable...` classes :) )
Can you pleas have a look?
> Activate info tests

- co_sim_io/impl/co_sim_io_impl.hpp
- co_sim_io/impl/info.hpp
- co_sim_io/impl/version.hpp
This adds the Version, pretty similar to how it is done in Kratos
two questions:
- would you prefer to have this more accessible? I.e. in the `CoSimIO` namespace and not in the `CoSimIO::Internals` namespace?
- would you prefer to have the version as `#define` like it is done in Kratos?
Only thing I am not sure yet is how to generate the hash yet (bcs it is header-only), but this can most likely be done by an actions after every merge
I would not do this atm, IMO it is not that important for now
> Add version

- CMakeLists.txt
- tests/CMakeLists.txt
- tests/solver_integration/cpp_solver/hello.cpp
This will automatically detect any cpp in the cpp_solver folder. Using the ctest botton in the Code status bar restuls in:
```
[proc] Executing command: /usr/bin/ctest -j34 -C Debug -T test --output-on-failure
[ctest] Cannot find file: /home/pooyan/Developments/CoSimIO/build/DartConfiguration.tcl
[ctest] Cannot find file: /home/pooyan/Developments/CoSimIO/build/DartConfiguration.tcl
[ctest]    Site: 
[ctest]    Build name: (empty)
[ctest] Test project /home/pooyan/Developments/CoSimIO/build
[ctest]     Start 1: hello_cpp_test
[ctest] 1/1 Test #1: hello_cpp_test ...................   Passed    0.01 sec
[ctest] 
[ctest] 100% tests passed, 0 tests failed out of 1
[ctest] 
[ctest] Total Test time (real) =   0.01 sec
[ctest] CTest finished with return code 0
```
> Adding cpp ctests

- tests/co_sim_io/internals/test_info.cpp
for me it also works with a `char*` without adding a new function
> Info: adding test with char*

- co_sim_io/impl/co_sim_io_impl.hpp
- co_sim_io/impl/connection.hpp
now the `connection_status` should be working as you describe in the tutorial
> adding connection_status

- co_sim_io/python/co_sim_io_python.cpp
I needed the `Export...` wrappers after all, since those fct are templated in C++ :)
Now the python interface should be ready
> Missing updates in Py-interface

- CMakeLists.txt
now works the same as in Kratos
> override only for gcc > 5

- co_sim_io/python/co_sim_io_python.cpp
- co_sim_io/python/connection_status_to_python.hpp
- co_sim_io/python/info_to_python.hpp
- co_sim_io/python/version_to_python.hpp
this way it can be directly reused in Kratos and does not have to be copy-pasted
(I didn't separate into header&source yet to make it easier to use. Could be done in the future if required)
> modularize py-exposure

- .github/workflows/ci.yml
- tests/integration_tutorials/c/export_import_data.c
- tests/integration_tutorials/c/export_import_mesh.c
- tests/integration_tutorials/c/import_mesh.c
currently only in C++ the warnings are turned into errors.
This PR does the same for C
=> this will need fixes in some `printf` functions
> adding Werror to C-flags

- co_sim_io/impl/version.hpp
- tests/co_sim_io/impl/test_include_co_sim_io_1.cpp
- tests/co_sim_io/impl/test_include_co_sim_io_2.cpp
@pooyan-dadvand looks like we forgot an inline :D
In any case now I added a test such that we are sure `co_sim_io.hpp` can be safely included in multiple source files
> Missing inline and test

- tests/co_sim_io/impl/co_sim_io_testing.hpp
FYI @pooyan-dadvand when using this Macro in a loop that has the same counter variable (`i` in my case) this was not working, after the macro unrolling it was using the same variable :facepalm: 
@roigcarlo [Kratos has the same issue,](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/checks.h#L58-L153) just that apparently it wasn't detected there yet
> fixing check macros by "hiding" counters

- co_sim_io/impl/define.hpp
- co_sim_io/impl/model_part.hpp
- co_sim_io/impl/utilities.hpp
- co_sim_io/python/model_part_to_python.hpp
- tests/co_sim_io/impl/test_model_part.cpp
- tests/co_sim_io/python/test_model_part.py
@pooyan-dadvand this PR improved the `ModelPart` to make the construction of Elements more clear.
Before one had to directly give the vtk cell number identifier (e.g. 5 for a triangle), now this can be explicitly specified. I like this much more, not sure why I haven't thought of it initially :)
Also now I can make sure the correct number of nodes is given for a specific geometry. I.e. now I can no longer use e.g. triangle and pass only 2 nodes in the construction of an element
> ModelPart proper element types

- co_sim_io/impl/co_sim_io_impl.hpp
- co_sim_io/impl/communication/communication.hpp
One step in the direction of cleaning the interface
this time removing the old versions of `ImportData` and `ExportData`
FYI @pooyan-dadvand
> removing old interfaces of I/E-Data

- co_sim_io/python/co_sim_io_python.cpp
- co_sim_io/python/vector_to_python.hpp
- tests/co_sim_io/python/test_vector.py
- tests/integration_tutorials/python/export_data.py
- tests/integration_tutorials/python/import_data.py
This PR adds the `CoSimIO.Vector`
this object is a tiny wrapper around `std::vector<double>` to be used in Python. The goals are:
- Make the data exchange more efficient, having a dedicated object will not require to copy back and forth the data each time (currently pybind does this automatically each time we pass data btw Python & C++)
- The interfaces are now unified, esp for the `ImportData` we will not need to return a tuple (of `CoSimIO.Info` & the data (a `py::list`)) any more but now only the `Info`
=> the Interface will be updated in a follow up PR
> [Python] adding Vector

- co_sim_io/c/co_sim_io_c.cpp
- co_sim_io/c/co_sim_io_c_info.h
- tests/co_sim_io/c/info/test_info_copy.c
this adds a method for C to copy the `Info` (essentially calling the Copy-CTor of C++)
Same is already possible for python and C++
> [C] copy Info

- co_sim_io/impl/communication/file_communication.hpp
- tests/co_sim_io/impl/test_communication.cpp
this PR intends to tackle some concurrency issues in Win
The issue with Win is that the file cannot be deleted if another handle to it exists. This can be the case for us if the partner is checking if the file (still) exists. In this case it would crash.
I improved this situation by adding an index to the files such that the file names are "unique" and less concurrency issues occur (sometimes can still happen since I explicitly use some files for synchronization)
I had this idea in the past already to have a buffer of files to not block the caller aka make the comm more async.
Furthermore this can be very useful in the future if we want to keep the files (sort of as a history) for debugging
> Improve file access concurrency issues

- co_sim_io/impl/communication/file_communication.hpp
- co_sim_io/impl/version.hpp
- co_sim_io/python/co_sim_io_python.cpp
- tests/integration_tutorials/c/hello.c
- tests/integration_tutorials/cpp/hello.cpp
- tests/integration_tutorials/python/hello.py
now the `Connect` also checks if the versions are compatible
for now it is a quite basic check, in the future when we need to communicate more things I would refactor to use `ImportInfo` & `ExportInfo`
> File comm/check version

- co_sim_io/python/co_sim_io_python.cpp
- co_sim_io/python/connection_status_to_python.hpp
- co_sim_io/python/info_to_python.hpp
- co_sim_io/python/model_part_to_python.hpp
- co_sim_io/python/vector_to_python.hpp
- co_sim_io/python/version_to_python.hpp
in #118 I introduced `PYBIND11_MAKE_OPAQUE`
When integrating this in Kratos (https://github.com/KratosMultiphysics/Kratos/pull/8363) I noticed that it messes up the remaining python interface of Kratos
Hence I am reverting this and bring back the manual exposure of `std::vector`
> [Python] manually exposing std vector

- CHANGELOG.md
- co_sim_io/c/co_sim_io_c.cpp
- tests/co_sim_io/c/model_part/test_model_part.c
- tests/co_sim_io/impl/test_model_part.cpp
- tutorial/c/README.md
- tutorial/c/model_part.md
- tutorial/cpp/README.md
- tutorial/cpp/model_part.md
- tutorial/python/README.md
- tutorial/python/model_part.md
This PR adds the things we discussed earlier:
- Changelog
- big improvements in the tutorial: Adding large documentation for `ModelPart`
> Tutorial improvements

- co_sim_io/c/co_sim_io_c.h
- co_sim_io/c/co_sim_io_c_info.h
- co_sim_io/c/define_c.h
I found a way to emulate `nodiscard` in C :) (with GCC and clang)
Apparently it will be added in C23: https://en.cppreference.com/w/c/language/attributes/nodiscard
this is how the warning message looks like:
~~~
home/philipp/software/CoSimIO/tests/integration_tutorials/c/export_mesh.c:87:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
CoSimIO_CreateInfo();
~~~
I would say this is better than manually keeping track of the `CoSimIO_Info`, what do you think @pooyan-dadvand ?
Changelog:
~~~
- creating CO_SIM_IO_NODISCARD to warn when memory is leaked from CoSimIO_Info
~~~
> [C] adding nodiscard for CoSimIO_Info

- tests/CMakeLists.txt
- tests/test_fail.cpp
- tests/test_success.cpp
At the moment the script `run.sh` (which we use to run the coupled examples) returns the return code of the last executed command!
I.e. if the first one fails this is not detected!
This PR fixes this and also adds tests
useful reference:
https://superuser.com/questions/461432/get-exit-code-from-subshells-that-are-running-in-parallel
> [Testing] fixing return values in run.sh script

- docs/api_docs/README.md
As discussed @pooyan-dadvand, this adds the syntax for the different languages to the API docs, same as in the MPI docs
> [doc] adding syntax to API documentation

- external_libraries/doctest/doctestAddTests.cmake
- tests/CMakeLists.txt
issue is described here: https://github.com/catchorg/Catch2/pull/2039
In a nutshell: On win the dll is not found
I will also push this upstream
> Fix test WORKING_DIRECTORY

- .github/workflows/ci.yml
- CMakeLists.txt
- tests/filter_valgrind_suppressions.py
- tests/valgrind_suppressions.supp
The intel compiler was updated yesterday (`2021.2.0` -> `2021.3.0`)
this produces some more valgrind errors, this PR suppresses those too
Also I am uploading the test logs now as artifacts in case they fail, this will make debugging much less painful
> Fix tests after intel update

- .github/workflows/ci.yml
- tests/CMakeLists.txt
leftover of #202 
doctest needs to run the test executable to determine the names of the test cases. For this I need to know the location of the shared lib `co_sim_io`
Hopefully this works with the generator expression
> [Testing] generator expression for location of shared lib

- .github/workflows/ci.yml
- external_libraries/doctest/doctest.cmake
- external_libraries/doctest/doctestAddTests.cmake
- tests/CMakeLists.txt
now the tests are listed as individual tests instead of adding the entire test runner
I.e. now it is consistent with the non-MPI tests :D
I will try to push the changes in doctest also upstream
> [MPI] enable CTest detection

- tests/co_sim_io/impl/co_sim_io_testing.hpp
now one can directly pass:
```c++
std::shared_ptr<std::vector<...>> p_vec;
CO_SIM_IO_CHECK_VECTOR_NEAR(*p, ...)
```
before it had to be used as:
```c++
std::shared_ptr<std::vector<...>> p_vec;
CO_SIM_IO_CHECK_VECTOR_NEAR((*p), ...)
```
using it without `()` caused some confusing compiler errors
> warding variables in check macros

- co_sim_io/c/CMakeLists.txt
and not globally
simplification of #216
> setting WINDOWS_EXPORT_ALL_SYMBOLS only on C-lib directly

- co_sim_io/impl/data_container.hpp
- tests/co_sim_io/impl/test_data_container.cpp
the behavior needs to be the same so that we can serialize to and from different types
necessary e.g. when going from C (raw memory based) to Python (std::vector based)
> [DataContainer] improve serialization

- CMakeLists.txt
- adding a flag for debug: `CO_SIM_IO_DEBUG` (same as `KRATOS_DEBUG`)
- more warnings activated: `Wextra` in GCC & Clang
> adding more flags in CMake

- co_sim_io/includes/info.hpp
- co_sim_io/sources/info.cpp
those are no longer needed since we now use the `Serializer`
Also I slightly refactored the `Name` methods for easier extensibility
> [Info] removing old Save/Load methods

- co_sim_io/includes/define.hpp
needed as some IPC methods are plattform dependent
very basic version, we can easily extend it if necessary
> adding macro detection for Win

- .github/workflows/ci.yml
- tests/co_sim_io/c/info/test_info_double.c
when using valgrind, can be useful for debugging
> [CI] always upload logs of CTest

- co_sim_io/sources/communication/communication.cpp
for some reason the `filesystem::exists` function throws sometimes, guess it crashes when there are race conditions, as the win file access fcts are not atomic by default.
By adding the error code the fct should not crash but populate the error code instead (in which I am not interested)
Lets see if this improves the random errors
> adding error code

- co_sim_io/includes/communication/communication.hpp
- co_sim_io/sources/communication/communication.cpp
- tests/co_sim_io/cpp/test_communication.cpp
As of now for the file communication we create the file with a temp name when writing to it in order to avoid race conditions when accessing it.
E.g. when writing to `data_abc.dat`, the sender writes it in `.data_abc.dat` to hide it from the receiver. Once the writing is done, it is renamed to `data_abc.dat` so that the receiver can see it. Unfortunately on some OSs (e.g. Windows), `rename` is not atomic and race conditions can occur. I implemented several safety mechanisms to prevent this from happening, but it is not impossible to happen.
Hence this PR introduces a new method to solve this problem: Instead of renaming the file, an auxiliary file is written, which indicates that the original file is ready to be read.
It seems to work well, we have to see how it behaves in practice
I also …
> [Communication] option to use availability file instead of rename

- co_sim_io/includes/communication/communication.hpp
- co_sim_io/includes/utilities.hpp
- co_sim_io/sources/communication/file_communication.cpp
- co_sim_io/sources/utilities.cpp
- tests/CMakeLists.txt
- tests/co_sim_io/cpp/test_utilities.cpp
- tests/integration_tutorials/cpp/mpi/export_data_mpi.cpp
- tests/integration_tutorials/cpp/mpi/export_mesh_mpi.cpp
- tests/integration_tutorials/cpp/mpi/import_data_mpi.cpp
- tests/integration_tutorials/cpp/mpi/import_mesh_mpi.cpp
This PR makes the FileCommunication MPI-compatible
So far it is necessary to use the same number or cores for both sides, this will be improved in a future PR
Some basic tests are added
> [FileComm] making MPI compatible

- co_sim_io/includes/model_part.hpp
- tests/co_sim_io/cpp/test_model_part.cpp
I find it quite annoying that in order to loop the nodes one has to do:
~~~c++
for (auto node_it=model_part.NodesBegin(); node_it!=model_part.NodesEnd(); ++node_it) {
(*node_it)->Id()
}
~~~
this PR adds support for range based loops:
~~~c++
for (auto& r_node : model_part.Nodes()) {
r_node->Id()
// r_node.Id() // this is done using boost::indirect_iterator in Kratos. 
// We could implement our own iterator but not sure if it is worth it ...
}
~~~
lets discuss the implementation
> [ModelPart] support for range based loops

- co_sim_io/includes/communication/pipe_communication.hpp
- co_sim_io/sources/communication/pipe_communication.cpp
`read` and `write` return a count variable that should not be discarded
Now checking the return value of these fcts
More info see the docs of read and write:
- https://man7.org/linux/man-pages/man2/read.2.html
- https://man7.org/linux/man-pages/man2/write.2.html
> Fix pipe comm warnings

- co_sim_io/includes/communication/communication.hpp
- co_sim_io/includes/communication/pipe_communication.hpp
- co_sim_io/includes/communication/socket_communication.hpp
- co_sim_io/includes/define.hpp
- co_sim_io/sources/communication/pipe_communication.cpp
- co_sim_io/sources/communication/socket_communication.cpp
- docs/communication.md
Improvements:
- Now it is possible to input the IP-address that should be used
- Alternatively the name of the network can be used to determine the IP address (only available on linux) => mostly useful for Clusters to select e.g. the infiniband network
- Communication of vector data is now done without serialization which in my prelim tests was ~10 times faster
> Improving SocketComm

- co_sim_io/includes/communication/socket_communication.hpp
- co_sim_io/sources/communication/socket_communication.cpp
Now the primary connection dictates the selection of the IP address that is used.
Reason is than in distributed memory each compute-node has its own ip address, and hence only one of them can be used
> [SocketComm] bugfix for distributed memory

- co_sim_io/includes/communication/communication.hpp
- co_sim_io/includes/communication/file_communication.hpp
- co_sim_io/sources/communication/communication.cpp
- co_sim_io/sources/communication/file_communication.cpp
- docs/communication.md
- tests/co_sim_io/cpp/test_communication.cpp
on windows, renaming files is not atomic and can cause race conditions, hence using aux fles for the synchronization there.
On unix the default is to rename files, which is especialy good for the cluster as then least amount of files is used
> [FileComm] improve how files are made available

- co_sim_io/sources/communication/communication.cpp
This should allow that one side uses elevated (i.e. sudo or admin) privileges while the other one does not. I solve this by giving each file that is created equal permissions.
With the proposed solution it works for me on linux, but I cannot reproduce the problem in my Windows setup (regular Win10 with VS2019)
> Set file permissions correctly

- co_sim_io/fortran/co_sim_io.f90
- tests/co_sim_io/fortran/connect_disconnect.f90
Fortran Interface for:
- co_sim_io_c.h
- co_sim_io_c_info.h
- co_sim_io_c_model_part.h
New fuctions:
- CoSimIO_Info_GetString_Wrapper: wrapper for CoSimIO_Info_GetString()
- CoSimIO_ModelPart_Name_Wrapper: wrapper for CoSimIO_ModelPart_Name()
> Adding new fortran wrapper for CoSimIO

- docs/model_part/model_part_cpp.md
Fixed minor typo in the variable names from the documentation on how to use the Element class from ModelPart.
> Fixed variable name in Element use

- co_sim_io/includes/communication/local_socket_communication.hpp
- co_sim_io/includes/communication/socket_communication.hpp
- co_sim_io/sources/communication/communication.cpp
- co_sim_io/sources/communication/pipe_communication.cpp
some old kernels don't define those, hence checking before using them
> Fix pipe defines old kernels

- CMakeLists.txt
Allow `CMake` to set `RPath` in built binaries when installing on MacOS. This fixes an issue when compiling `CoSimIO` from `KratosMultiphysics`, where loading `CoSimIO` failed due expired library paths after installing. 
*P.S.: I don't have much experience on MacOS, so please go easy on me.*
> MacOS RPath

- co_sim_io/sources/code_location.cpp
- external_libraries/ghc/filesystem.hpp
- tests/co_sim_io/c/mpi/dummy_mpi_test.c
- tests/co_sim_io/cpp/test_code_location.cpp
fixes #350
FYI @loumalouomega this is a slightly improved version of #351, including a test
> Fix code loc win

- scripts/build.bat
- scripts/build_and_test.bat
- scripts/build_c.bat
- scripts/build_cpp.bat
- scripts/build_python.bat
This PR introduces a set of new build scripts for Windows OS. These scripts are added to the "scripts" directory and serve various purposes. Here's a brief overview of the changes made:
1. `scripts/build.bat`: This script sets up the compiler and various environment variables, then configures and builds the project using CMake. It also includes options to control the build type, enable/disable testing, and build components like C, Python, and Fortran.
2. `scripts/build_and_test.bat`: This script is designed to be run from the build directory. It invokes the `scripts/build.bat` script with specific options and then runs CTests for testing the project. Afterward, it runs Python tests.
3. `scripts/build_c.bat`: This script is used to build the C component of the project by calling the …
> [Scripts] Adding Windows scripts

- docs/tutorials/c/integration_co_sim_io.md
- docs/tutorials/cpp/integration_co_sim_io.md
- docs/tutorials/python/integration_co_sim_io.md
This PR updates the documentation for integrating the *CoSimIO* library into C++, C, and Python projects. It provides detailed instructions for each language on how to compile and integrate *CoSimIO* for Windows. The changes include the addition of build scripts for different platforms and improved clarity in the documentation.
- In the C integration documentation, it separates the instructions for Linux/MacOS and Windows users, providing links to relevant build scripts.
- In the C++ integration documentation, idem.
- In the Python integration documentation, idem.
Overall, these changes make it easier for developers to integrate *CoSimIO*into their projects in various programming languages in Windows OS.
> [Documentation] Update documentation for CoSimIO integration in C++, C, and Python for Windows

- co_sim_io/includes/communication/pipe_communication.hpp
- co_sim_io/sources/communication/pipe_communication.cpp
- scripts/build.bat
This PR updates the 'scripts/build.bat' file. The changes include setting the compiler variables 'CC' and 'CXX' based on the value of 'USE_INTEL_LLVM', and adjusting the 'CO_SIM_IO_STRICT_COMPILER' setting accordingly. When 'USE_INTEL_LLVM' is 'ON', it sets the compiler to 'icx-cl.exe' and turns off the strict compiler mode, as the Intel LLVM compiler fails with strict compiler settings. 
When 'USE_INTEL_LLVM' is 'OFF', it sets the compiler to 'cl.exe' and turns on the strict compiler mode. 
These changes are required fir for proper compilation on Windows systems when using the Intel LLVM compiler.
> Initial support LLVM Intel in Windows

- .github/workflows/ci.yml
Adding the new intel compiler to the CI
> Adding ICX in CI
