co_sim_io/impl/info.hpp, tests/co_sim_io/internals/test_info.cpp
the implementation is quite basic for now, but I think it serves our purpose perfectly
=> [Info] add serialization

co_sim_io/co_sim_io.hpp, co_sim_io/impl/co_sim_io_impl.hpp
just a first version, we can improve it later
=> adding first version of Hello

co_sim_io/impl/info.hpp, tests/co_sim_io/internals/test_info.cpp
now the `Info` ca be printed
looks e.g. like this:
~~~
CoSimIO-Info; containing 5 entries
name: checking | value: 22 | type: int
name: echo_level | value: 2 | type: int
name: is_converged | value: 1 | type: bool
name: keyword | value: awesome | type: string
name: tol | value: 0.008 | type: double
~~~
=> Info ostream operator

co_sim_io/impl/info.hpp, co_sim_io/python/co_sim_io_python.cpp, tests/co_sim_io/python/__init__.py, tests/co_sim_io/python/test_info.py
This add the python-exposure of the `CoSimIO::Info`
Tests are added (ported the c++ tests to python)
=> Info Python exposure

co_sim_io/impl/info.hpp, tests/co_sim_io/impl/test_info.cpp
Adds assignment operator and copy constructors to the Info. Tests are also provided
=> Fixing info assignment

tests/CMakeLists.txt
Now it runs two executables in pair
=> Fixing connect disconnect test

tutorial/cpp_tutorials/README.md
ImportMesh was missing in tutorial
=> Adding import mesh

CMakeLists.txt, external_libraries/catch2/Catch.cmake, external_libraries/catch2/CatchAddTests.cmake, tests/CMakeLists.txt
now the tests for the CoSimIO are no longer added as one test to CTests but as individual tests
=> Catch2 tests in ctests

co_sim_io/c/co_sim_io_c.cpp, co_sim_io/c/co_sim_io_c.h, co_sim_io/impl/data_container.hpp
missing fixes for the C-Interface
I also updated the `ExportData` interface to make it easier to use
=> Fix C Im/Export mesh

README.md, co_sim_io/impl/communication/file_communication.hpp, co_sim_io/impl/filesystem_inc.hpp, external_libraries/ghc/filesystem.hpp
this introduces the C++11 compatible version of `std::filesystem`, the same one that we use in Kratos
https://github.com/gulrak/filesystem
We can discuss this but honestly I think there is no way around it, there are too many problems with deadlocking etc that make life quite hard even as a developer
good thing that this will become obligatory when moving to C++17
=> Add filesystem

co_sim_io/impl/co_sim_io_impl.hpp
This was missing
It is already fixed in Kratos
=> fixing SendControlSignal

co_sim_io/c/co_sim_io_c.cpp, tests/integration_tutorials/c/import_mesh.c
This fixes the return argument error in the c interface
@philbucher I think we may need to release a hot fix with this change.
=> Fix c import mesh

tutorial/c/README.md
my suggestions, the rest looks good! :+1: 
Since those are general instructions not related to `C` I would move it to another place such that it can be used also for the other languages
=> Suggestions for tutorial

tutorial/c/README.md, tutorial/cpp/README.md, tutorial/python/README.md
FYI @pooyan-dadvand just to keep the overview a bit better
=> Adding overview to tutorials

co_sim_io/python/info_to_python.hpp, tests/co_sim_io/python/test_info.py
FYI @pooyan-dadvand I think this can be useful
also maybe we can add it to the C-Interface
=> Expose Info copy ctor to python

co_sim_io/python/info_to_python.hpp, tests/co_sim_io/python/test_info.py
=> Python expose len of Info

co_sim_io/impl/data_container.hpp
now that we have this `Info` this was sorta replaced / would anyway have to be implemented in a different way if needed
=> clean data_container.hpp

tests/co_sim_io/impl/test_info.cpp
properly using the features of the testing library, but not yet fully exploited
=> Improve info tests

co_sim_io/impl/data_container.hpp, co_sim_io/impl/define.hpp, scripts/build_and_test.sh, tests/co_sim_io/impl/co_sim_io_testing.hpp, tests/co_sim_io/impl/test_data_container.cpp
This PR adds the tests for `DataContainer` as well as major improvements for the version with raw memory
=> Data container improvements

tutorial/python/README.md
=> adding explanation on how to specify python

co_sim_io/impl/communication/communication.hpp, co_sim_io/impl/communication/file_communication.hpp
thats basically it
I update the public interfaces, so that I can implement them in the `FileCommunication` in a separate PR
once that is done I can propagate the changes "upwards" and finally change the Interface of the `CoSimIO`
=> [Communication] Update interfaces to work with Info

co_sim_io/impl/communication/communication.hpp
this was discussed at some point, now it will be more versatile
=> [Communication] changing to Import/ExportInfo

CMakeLists.txt
minor PR to find the external libs that we will need in the future
This won't be operational / needed in production anytime soon, but it simplifies my testings as I am currently refactoring a bit the `Communication` class
=> finding Boost and MPI

external_libraries/doctest/doctest.h, external_libraries/doctest/extensions/doctest_mpi.h, external_libraries/doctest/extensions/doctest_util.h, external_libraries/doctest/extensions/mpi_reporter.h
FYI @pooyan-dadvand
this version now also has MPI support, hope I can try it soon
=> updated doctest to version 2.4.1

co_sim_io/impl/communication/communication.hpp, co_sim_io/impl/communication/file_communication.hpp, tests/co_sim_io/impl/co_sim_io_testing.hpp, tests/co_sim_io/impl/test_communication.cpp
this time the Import-/ExportData functions are updated
Furthermore, more tests are added
=> [Communication] more updates to use new functions

co_sim_io/c/co_sim_io_c.cpp, co_sim_io/c/co_sim_io_c.h, co_sim_io/c/co_sim_io_c_model_part.h, co_sim_io/co_sim_io.hpp, co_sim_io/impl/co_sim_io_impl.hpp, co_sim_io/impl/communication/communication.hpp, co_sim_io/impl/communication/file_communication.hpp, co_sim_io/python/co_sim_io_python.cpp
this starts to use the `ModelPart` for `ImportMesh` & `ExportMesh`
@pooyan-dadvand I think we should speak next week about this, some things related to the C-Interface are not clear to me
=> C ModelPart

.github/workflows/ci.yml
=> [CI] using 2 threads for building

scripts/build.sh, scripts/build_c.sh, scripts/build_python.sh
[Looking at the same in Kratos](https://github.com/KratosMultiphysics/Kratos/blob/master/scripts/standard_configure.sh#L48) this should work I think
can you please confirm @roigcarlo ? Thx!
=> using parallel build

tests/CMakeLists.txt, tests/co_sim_io/c/info/test_info_bool.c, tests/co_sim_io/c/info/test_info_clear.c, tests/co_sim_io/c/info/test_info_double.c, tests/co_sim_io/c/info/test_info_erase.c, tests/co_sim_io/c/info/test_info_int.c, tests/co_sim_io/c/info/test_info_multiple_vals.c, tests/co_sim_io/c/info/test_info_print.c, tests/co_sim_io/c/info/test_info_size.c, tests/co_sim_io/c/info/test_info_string.c
moving some tests to a subfolder to keep better overview
=> moving tests to subfolder

co_sim_io/impl/communication/file_communication.hpp
this has quite a significant influence on the test times
Probably for real cases it is not that noticeable though
FYI @pooyan-dadvand
=> reduce wait time in FileCommunication

co_sim_io/impl/co_sim_io_impl.hpp, co_sim_io/impl/communication/communication.hpp, co_sim_io/impl/communication/file_communication.hpp, co_sim_io/impl/connection.hpp
=> cleaning old interfaces & functions

.github/workflows/ci.yml, co_sim_io/impl/communication/file_communication.hpp, scripts/build.sh, scripts/build_and_test.sh
now with proper handling of paths
=> [FileCommunication] using fs::path over std::string

.github/workflows/ci.yml, co_sim_io/impl/connection.hpp, tests/integration_tutorials/cpp/runner.cpp, tests/integration_tutorials/python/run.py, tests/integration_tutorials/python/runner.py, tests/integration_tutorials/python/test_python_interface.py
=> [Python] adding test for Run method

co_sim_io/impl/communication/communication.hpp, co_sim_io/impl/communication/file_communication.hpp, tests/integration_tutorials/python/test_python_interface.py
minor cleanup to avoid printing double quotes
=> Path is already quoted

.github/workflows/ci.yml
=> [CI] adding Python 3.9

co_sim_io/impl/communication/file_communication.hpp
=> give sync file a name

co_sim_io/c/co_sim_io_c.cpp, co_sim_io/c/co_sim_io_c_model_part.h, co_sim_io/impl/model_part.hpp, co_sim_io/python/model_part_to_python.hpp, tests/co_sim_io/c/model_part/test_model_part.c, tests/co_sim_io/impl/test_model_part.cpp, tests/co_sim_io/python/test_model_part.py
I think this makes sense to have when importing / exporting meshes
If you agree I will add tests and expose it in the other languages @pooyan-dadvand
=> [ModelPart] adding clear

.github/workflows/ci.yml
this PR only installs MPI and prepares it for the MPI extensions
=> [CI] install MPI

.github/workflows/ci.yml
this PR prepares the python build for MPI testing
it also adds an intel build as we had issues with this in the past
=> [CI] preparing python MPI tests

.github/workflows/ci.yml, CMakeLists.txt, tests/CMakeLists.txt, tests/co_sim_io/c/mpi/dummy_mpi_test.c
initial add of tests for MPI in the C-Interface
Also adds a dummy test
=> [C] initial add of MPI testing infrastructure

docs/_config.yml
I find this to look better
the other one (currently used) was only a test
=> [Docs] using leap day theme

README.md, docs/index.md
related to the detached interface
=> More minor updates in documentation

.github/workflows/ci.yml
seems like otherwise it won't find some packages
=> [CI][Python] adding apt-get update

docs/tutorials/README.md, docs/tutorials/cpp/basic_data_exchange_with_kratos.md, docs/tutorials/cpp/data_and_mesh_exchange_and_mapping.md, docs/tutorials/cpp/mesh_exchange_with_kratos.md, tests/integration_tutorials/cpp/data_exchange.cpp, tests/integration_tutorials/cpp/mesh_exchange.cpp
=> [Docs] tutorial for mesh exchange with Kratos (C++)

CMakeLists.txt, co_sim_io/co_sim_io_mpi.hpp, co_sim_io/src/mpi/co_sim_io_mpi.cpp, tests/CMakeLists.txt
=> [MPI] split header source

CMakeLists.txt, co_sim_io/co_sim_io.hpp, co_sim_io/impl/code_location.h, co_sim_io/impl/communication/sockets_communication.hpp, co_sim_io/impl/connection.hpp, co_sim_io/impl/utilities.hpp, co_sim_io/impl/vtk_utilities.hpp, co_sim_io/src/code_location.cpp, co_sim_io/src/communication/sockets_communication.cpp, co_sim_io/src/connection.cpp, co_sim_io/src/utilities.cpp, co_sim_io/src/version.cpp, co_sim_io/src/vtk_utilities.cpp
see title, splitting some headers into header-source
This is a nice cleanup of the includes!
=> Split header sources

co_sim_io/impl/communication/communication.hpp, co_sim_io/impl/communication/file_communication.hpp, co_sim_io/impl/model_part.hpp, co_sim_io/src/communication/communication.cpp, co_sim_io/src/communication/file_communication.cpp, co_sim_io/src/model_part.cpp
splitting `model_part.hpp` and `communication.hpp`
=> Split more header sources

co_sim_io/impl/model_part.hpp
now it doesn't have to be added to every new CTor
=> improve initialization of referencecounter

.github/docker_files/docker_file_ci_ubuntu_20_04/DockerFile, .github/workflows/build_docker_images_for_ci.yml
Mostly bcs the Intel compiler often fails to install
=> [CI] adding Docker for Linux

co_sim_io/impl/info.hpp, co_sim_io/src/info.cpp, tests/co_sim_io/impl/test_info.cpp
This PR adds serialization to the `Info` by using the newly added `Serializer`
=> Info - adding serialization

co_sim_io/impl/model_part.hpp, co_sim_io/src/model_part.cpp, tests/co_sim_io/impl/co_sim_io_testing.cpp, tests/co_sim_io/impl/co_sim_io_testing.hpp, tests/co_sim_io/impl/test_model_part.cpp
Using the newly added `Serializer`
=> [ModelPart] adding serialization

co_sim_io/impl/data_container.hpp, tests/co_sim_io/impl/test_data_container.cpp
Final PR related to serialization
=> [DataContainer] adding serialization

co_sim_io/impl/communication/file_communication.hpp, co_sim_io/impl/utilities.hpp, co_sim_io/impl/vtk_utilities.hpp, co_sim_io/src/communication/file_communication.cpp, co_sim_io/src/vtk_utilities.cpp, tests/co_sim_io/impl/test_vtk_utilities.cpp
since I want to use the Serializer for exchanging data I will no longer need this
still would be sad to remove it, hence leaving it in a separate fct for now
=> Refactor writing and reading of vtk to separate functions

docs/tutorials/co_sim_classical_approach.md, docs/tutorials/kratos_co_simulation.md
still needs some improvements but I think it is a good start
=> CoSimulation tutorial for classical approach

co_sim_io/impl/stream_serializer.hpp, co_sim_io/src/stream_serializer.cpp
required for e.g. MPI data exchange
=> [StreamSerializer] add CTor that accepts string

CMakeLists.txt, co_sim_io/includes/communication/communication.hpp, co_sim_io/includes/define.hpp, co_sim_io/includes/exception.hpp, co_sim_io/sources/communication/communication.cpp, co_sim_io/sources/communication/file_communication.cpp, co_sim_io/sources/exception.cpp, scripts/build.sh
same as in Kratos, it is very useful for finally debugging the race conditions of the FileCommunication in Win
=> Adding try catch

co_sim_io/includes/info.hpp
=> [Info] validating types in every fct

co_sim_io/includes/connect_impl.hpp, co_sim_io/sources/co_sim_io.cpp, co_sim_io/sources/connect_impl.cpp, co_sim_io/sources/mpi/co_sim_io_mpi.cpp, co_sim_io/sources/mpi/mpi_data_communicator.cpp
And using the `DataCommunicator` resp `MPIDataCommunicator`
In the next PR I will pass the `DataCommunicator` to the `Connection` and from there to the `Communication`
=> [MPI] refactor & unify connecting

co_sim_io/includes/communication/communication.hpp, co_sim_io/includes/communication/file_communication.hpp, co_sim_io/includes/communication/sockets_communication.hpp, co_sim_io/includes/connection.hpp, co_sim_io/sources/communication/communication.cpp, co_sim_io/sources/communication/file_communication.cpp, co_sim_io/sources/communication/sockets_communication.cpp, co_sim_io/sources/connect_impl.cpp, co_sim_io/sources/connection.cpp, tests/co_sim_io/cpp/test_communication.cpp
So that the internal classes can use it
=> Passing DataCommunicator internally

co_sim_io/includes/info.hpp, co_sim_io/sources/info.cpp, tests/co_sim_io/cpp/test_info.cpp
see title, minor thing I overlooked
=> [Info] fix nested serialization

co_sim_io/includes/communication/file_communication.hpp, co_sim_io/sources/communication/communication.cpp, co_sim_io/sources/communication/file_communication.cpp
Not really needed as it doesn't solve the issue with the race condition when accessing files in Win
Plus is a blocker for async communication
=> [FileComm] remove file index

co_sim_io/includes/communication/communication.hpp, co_sim_io/includes/communication/file_communication.hpp, co_sim_io/sources/communication/communication.cpp, co_sim_io/sources/communication/file_communication.cpp, co_sim_io/sources/vtk_utilities.cpp
necessary for further developments
=> moving some file utility fcts to the baseclass

co_sim_io/mpi/sources/co_sim_io_mpi.cpp, co_sim_io/sources/communication/communication.cpp, co_sim_io/sources/communication/file_communication.cpp, tests/CMakeLists.txt, tests/integration_tutorials/cpp/mpi/connect_disconnect_mpi_a.cpp, tests/integration_tutorials/cpp/mpi/connect_disconnect_mpi_b.cpp
adding some corrections, missing synchronizations and tests for connecting and disconnecting in MPI
=> [MPI] Initial tests for connect/disconnect and missing synchronizations

co_sim_io/includes/communication/communication.hpp, co_sim_io/includes/communication/file_communication.hpp, co_sim_io/includes/communication/sockets_communication.hpp, co_sim_io/includes/data_communicator.hpp, co_sim_io/sources/communication/communication.cpp
now more checks for compatibility are done, futhermore the derived classes can implement their custom checks
Also it is possible for the derived classes to exchange some info now which might be necessarey for the conneciton (such as port addresses etc)
=> [Communication] improve handshake

co_sim_io/sources/communication/communication.cpp
doing some prints only on rank zero
=> [MPI] adding some wards for prints

co_sim_io/includes/communication/communication.hpp, co_sim_io/sources/communication/communication.cpp
minor fix for race condition when removing the comm folder
=> [Communication] fix race condition

co_sim_io/includes/define.hpp, co_sim_io/sources/info.cpp
only used so far bcs I use threads in the communication tests
=> make-info-serialization-threadsafe

co_sim_io/mpi/sources/mpi_data_communicator.cpp, tests/co_sim_io/cpp/mpi/test_mpi_data_communicator.cpp, tests/co_sim_io/cpp/test_data_communicator.cpp
=> fix macros names

co_sim_io/c/co_sim_io_c.cpp, co_sim_io/includes/utilities.hpp, co_sim_io/includes/vtk_utilities.hpp, co_sim_io/sources/communication/communication.cpp, co_sim_io/sources/communication/file_communication.cpp, co_sim_io/sources/communication/pipe_communication.cpp, co_sim_io/sources/connect_impl.cpp, co_sim_io/sources/model_part.cpp, co_sim_io/sources/utilities.cpp, co_sim_io/sources/vtk_utilities.cpp, tests/co_sim_io/cpp/co_sim_io_testing.hpp, tests/co_sim_io/cpp/test_utilities.cpp, tests/co_sim_io/cpp/test_vtk_utilities.cpp
see title
Needed for the communication among the ranks
=> [MPI] Function to compute partner ranks

docs/kratos_build.md, docs/mesh_connectivities.md, docs/model_part/model_part_c.md, docs/model_part/model_part_cpp.md, docs/model_part/model_part_python.md, docs/tutorials/c/integration_co_sim_io.md, docs/tutorials/co_sim_classical_approach.md, docs/tutorials/co_sim_remote_controlled.md, docs/tutorials/cpp/basic_data_exchange_with_kratos.md, docs/tutorials/cpp/integration_co_sim_io.md, docs/tutorials/cpp/mesh_exchange_with_kratos.md, docs/tutorials/kratos_co_simulation.md, docs/tutorials/python/integration_co_sim_io.md
This PR is created to provide the general self feedback on the CoSimIO Tutorials.
In general, everything looks very well organised, documented and detailed which explains the use of CoSimulation and CoSimIO. The presentation looks very well and also impressive.
1. Corrected some typos and links. 
2. Added some bash commands.
=> CoSimIO_Tutorials_Feedback

co_sim_io/includes/model_part.hpp
std::iterator is deprecated in C++17
=> using custom struct

CMakeLists.txt, co_sim_io/python/CMakeLists.txt
required as we have to support also old versions of CMake
nothing crucial
=> [CMake] fixing some warnings

.github/workflows/ci.yml, docs/build_options.md
=> [CI] adding build with ancient CMake

.github/workflows/ci.yml
=> [CI] missing cmd

co_sim_io/sources/communication/communication.cpp, co_sim_io/sources/communication/file_communication.cpp, tests/CMakeLists.txt, tests/integration_tutorials/cpp/mpi/connect_disconnect_mpi_a.cpp, tests/integration_tutorials/cpp/mpi/connect_disconnect_mpi_b.cpp, tests/integration_tutorials/cpp/mpi/export_data_mpi.cpp, tests/integration_tutorials/cpp/mpi/export_info_mpi.cpp, tests/integration_tutorials/cpp/mpi/export_mesh_mpi.cpp, tests/integration_tutorials/cpp/mpi/import_data_mpi.cpp, tests/integration_tutorials/cpp/mpi/import_info_mpi.cpp, tests/integration_tutorials/cpp/mpi/import_mesh_mpi.cpp
- Improve mpi-test registration
- check both sides use same number of processes
- cleaned FileComm since we decided to use the same number of processes on both sides
- minor MPI-test improvements
=> [MPI] some advances

co_sim_io/python/model_part_to_python.hpp, docs/model_part/model_part_cpp.md, docs/model_part/model_part_python.md, tests/co_sim_io/python/test_model_part.py
After #278 exposing the functionalities also in the Python interface
Documentation and tests are added
=> [Python] Adding GhostNode ModelPart interface

co_sim_io/c/co_sim_io_c.cpp, co_sim_io/c/co_sim_io_c_model_part.h, co_sim_io/includes/model_part.hpp, co_sim_io/python/model_part_to_python.hpp, docs/info/info_c.md, docs/info/info_cpp.md, docs/info/info_python.md, docs/model_part/model_part_c.md, docs/model_part/model_part_cpp.md, docs/model_part/model_part_python.md, tests/co_sim_io/c/model_part/test_model_part_ghost.c, tests/co_sim_io/python/test_model_part.py
After #278 exposing the functionalities also in the C interface
Documentation and tests are added
=> [C] Adding GhostNode ModelPart interface

.github/workflows/ci.yml, tests/co_sim_io/cpp/test_model_part.cpp
see title, not sure why this was not already there
=> cancel redundant builds in CI

README.md, docs/api_docs/README.md, docs/kratos_build.md, docs/tutorials/README.md, docs/tutorials/c/integration_co_sim_io.md, docs/tutorials/c/mpi.md, docs/tutorials/cpp/integration_co_sim_io.md, docs/tutorials/cpp/mpi.md, docs/tutorials/kratos_mapping.md, docs/tutorials/python/integration_co_sim_io.md, docs/tutorials/python/mpi.md, scripts/build_c.sh, scripts/build_cpp.sh, scripts/build_python.sh
Python will be updated once we agreed about the interface in #282
=> [Docs] adding MPI tutorials

CMakeLists.txt, co_sim_io/includes/define.hpp
changes to make integration in other codes (e.g. Kratos) possible
=> Integration fixes

co_sim_io/sources/communication/communication.cpp, co_sim_io/sources/utilities.cpp
As it still sometimes crashes in Win in those fcts
=> Catching exceptions in fs functions

README.md, co_sim_io/co_sim_io.hpp
=> Cleaing some leftovers

.github/workflows/ci.yml
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
=> using concurrency to cancel redundant builds

co_sim_io/includes/model_part.hpp, tests/co_sim_io/cpp/test_model_part.cpp
adding `size` and `operator+`
Helpful when passing around the containers of `Nodes` and `Elements`
=> Enhance pointer vector

.github/workflows/ci.yml, co_sim_io/includes/communication/pipe_communication.hpp, co_sim_io/sources/communication/pipe_communication.cpp, tests/co_sim_io/cpp/test_communication.cpp
now we can exchange data larger than the buffer size of the pipe
=> [PipeComm] enabling large data

co_sim_io/includes/communication/communication.hpp, co_sim_io/includes/communication/local_socket_communication.hpp, co_sim_io/includes/communication/pipe_communication.hpp, co_sim_io/includes/communication/socket_communication.hpp, co_sim_io/sources/communication/communication.cpp, co_sim_io/sources/communication/file_communication.cpp, co_sim_io/sources/communication/local_socket_communication.cpp, co_sim_io/sources/communication/pipe_communication.cpp, co_sim_io/sources/communication/socket_communication.cpp
now the timings are printed in the same way for all communication methods
=> Unify timing prints

co_sim_io/includes/info.hpp, co_sim_io/sources/info.cpp, tests/co_sim_io/cpp/test_info.cpp
I am reaching the limits of integers, hence adding support for `std::size_t`
=> [Info] adding support for std::size_t

co_sim_io/includes/communication/pipe_communication.hpp, co_sim_io/sources/communication/pipe_communication.cpp
now it is more failsafe and also the performance is improved due to larger buffer size
=> [PipeComm] improve buffer setting

.github/workflows/ci.yml, co_sim_io/sources/info.cpp
this was a race condition
only really mattered in the tests where I am using threads, didnt happen in real applications as we use different processes
=> first registering in Info

co_sim_io/sources/communication/base_socket_communication.cpp, co_sim_io/sources/communication/socket_communication.cpp
=> [SocketComm] free resources

README.md, co_sim_io/sources/connection.cpp, docs/communication.md
=> Changing default communication to sockets

.github/workflows/ci.yml
Python3.5 is no longer available
=> [CI] removed py 3.5

co_sim_io/includes/utilities.hpp, co_sim_io/sources/communication/communication.cpp, co_sim_io/sources/utilities.cpp
as it can cause problems in the communication a check is added which warns the user
=> Add check for endianness

.github/workflows/ci.yml, co_sim_io/includes/communication/factory.hpp, co_sim_io/includes/connect_impl.hpp, co_sim_io/includes/connection.hpp, co_sim_io/mpi/includes/communication/mpi_factory.hpp, co_sim_io/mpi/sources/co_sim_io_mpi.cpp, co_sim_io/mpi/sources/communication/mpi_factory.cpp, co_sim_io/sources/co_sim_io.cpp, co_sim_io/sources/communication/communication.cpp, co_sim_io/sources/communication/factory.cpp, co_sim_io/sources/connect_impl.cpp, co_sim_io/sources/connection.cpp, tests/co_sim_io/cpp/test_communication.cpp
In case we want to implement MPI-based communication at some point
=> Making comm factory more flexible

.github/workflows/ci.yml, CMakeLists.txt, co_sim_io/mpi/includes/communication/mpi_factory.hpp, co_sim_io/mpi/includes/communication/mpi_inter_communication.hpp, co_sim_io/mpi/sources/communication/mpi_factory.cpp, co_sim_io/mpi/sources/communication/mpi_inter_communication.cpp, co_sim_io/sources/communication/factory.cpp, co_sim_io/sources/communication/socket_communication.cpp, docs/build_options.md, docs/communication.md, scripts/build.sh, tests/integration_tutorials/cpp/mpi/export_mesh_mpi.cpp, tests/integration_tutorials/cpp/mpi/import_mesh_mpi.cpp
I managed to get it working after all, but as expected it has problems with OpenMPI
=> Adding MPI intercommunication

CMakeLists.txt, co_sim_io/sources/communication/communication.cpp, docs/communication.md
MPI_Ports is an MPI 2.0 feature
Adding a check and a warning to make sure it is available
=> adding configure check for MPI version

external_libraries/doctest/doctest.h, external_libraries/doctest/extensions/doctest_mpi.h, external_libraries/doctest/extensions/doctest_util.h, external_libraries/doctest/extensions/mpi_reporter.h, external_libraries/doctest/extensions/mpi_sub_comm.h
=> [Libs] Update the doctest external lib

co_sim_io/sources/code_location.cpp, co_sim_io/sources/version.cpp, tests/co_sim_io/cpp/test_code_location.cpp
As originally proposed in #351
=> use non-filesystem based way to get function name
